### ISSUE TITLE
Service hangs after few minutes

### ISSUE THREAD

**Issue by lunanigra** [info-beamer/package-32c3-screens#2]
Hello, I've set up a Raspberry PI with the latest Info Beamer release and tried the package-32c3-screens sample.

So far everything works fine; but when starting Info Beamer as service the sample hangs after just very few minutes. Starting the same script via console everything works fine.

```
/info-beamer/run
#!/bin/sh
export INFOBEAMER_ADDRESS=0.0.0.0
export INFOBEAMER_LOG_LEVEL=3

exec nice -n -5 ionice -c 1 -n 0 /var/info-beamer/bin/info-beamer /var/info-beamer/package-32c3-screens 2>&1
```

Any idea? Anything I can check? Could it be something with power management? I've configured the Raspberry PI to not start the X desktop - just console; without auto-login.

Thanks, JC

**Comment by dividuum** [comment]
What do you mean by "as service"? With systemd supervision? What firmware are you running? Some of the recent ones had a few crashes. What's the last line of output with log level `4`?

**Comment by lunanigra** [comment]
Hi, it's little strange... After having the problem the whole day it suddenly disappears - will continue testing.

With service I mean this...
https://info-beamer.com/blog/running-info-beamer-in-production

I'm trying the latest Raspian OS together with the current Info Beamer release.

```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by dividuum** [comment]
Can you check `vcgencmd version` and `uname -a`. Just for the record.

**Comment by lunanigra** [comment]
Sure... ;-)

**vcgencmd version**
```
Jun  7 2018 15:31:38 
Copyright (c) 2012 Broadcom
version 4800f08a139d6ca1c5ecbee345ea6682e2160881 (clean) (release)
```

**uname -a**
```
Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
```

**Comment by lunanigra** [comment]
I found what was missing... Unluckily I didn't add the run script inside the log folder.
Just the effect is 'interesting'.

And again, thanks for the cool tool :-)
